environment:
  matrix:
    - node_version: '8'
    - node_version: '10'
install:
  - ps: 'Install-Product node $env:node_version'
  - yarn install --frozen-lockfile
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - node --version
  - npm --version
  - yarn test
